=== Agridea/quantifarm-switzerland-platform/packages/data-platform/testcase-loader/json-schemas/Testcase.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://quantifarm.eu/ontology/Testcase.schema.json",
  "title": "QuantiFarm testcase data",
  "description": "Data collected in a QuantiFarm testcase to assess the functioning and performance of one or more DATS",
  "type": "object",
  "properties": {
    "testcaseNumber": {
      "description": "The unique number of the QuantiFarm testcase",
      "type": "integer"
    },
    "testcaseLeader": {
      "description": "The name of the leader of the QuantiFarm testcase",
      "type": "string"
    },
    "cultivationType": {
      "description": "The type of agricultural cultivation that is executed in the QuantiFarm testcase",
      "type": "string",
      "enum": ["Arable", "Horticulture", "Greenhouse", "Meat", "Milk", "Animals", "Oyster", "Bees", "Silos"]
    },
    "datsInformation": {
      "description": "List of the DATSs being applied in the QuantiFarm testcase",
      "type": "array",
      "items": {
        "description": "Generic information of a DATS being applied in the QuantiFarm testcase",
        "minItems": 1,
        "uniqueItems": true,
        "$ref": "https://quantifarm.eu/ontology/DatsInformation.schema.json"
      }
    },
    "yearlyAssessmentInformation": {
      "description": "List of years with one or more parcel comparisons and market information",
      "type": "array",
      "items": {
        "description": "Assessment information with parcel comparisons and market information for a single year",
        "uniqueItems": true,
        "$ref": "https://quantifarm.eu/ontology/YearlyAssessmentInformation.schema.json"
      }
    },
    "threeYearAverages": {
      "description": "List of three year averages of the main impact parameters that indicate how well the DATSs perform with respect to not using the DATSs",
      "type": "array",
      "items": {
        "description": "A three year average impact parameter that indicates how well the DATSs perform with respect to not using the DATSs",
        "uniqueItems": true,
        "$ref": "https://quantifarm.eu/ontology/ThreeYearAverages.schema.json"
      }
    }
  },
  "required": [ "testcaseNumber", "testcaseLeader", "cultivationType", "datsInformation", "yearlyAssessmentInformation"]
}

=== Agridea/quantifarm-switzerland-platform/packages/data-platform/testcase-loader/TC27.json
{
   "testcaseNumber": 27,
   "testcaseLeader": "Leuven",
   "cultivationType": "Milk",
   "datsInformation": [],
   "yearlyAssessmentInformation": [
      {
         "cultivationYear": 2023,
         "parcelComparison": [],
         "marketInformation": {
            "waterPrice": null,
            "fuelPrice": null,
            "electricityPrice": null,
            "averageSalary": null,
            "averageProfessionalSalary": null
         }
      },
      {
         "cultivationYear": 2024,
         "parcelComparison": [
            {
               "parcelAssessmentWithDATS": {
                  "farmInformation": {
                     "farmNumber": 1,
                     "biogeographicalRegion": "Continental",
                     "totalFarmSize": 75.6
                  },
                  "parcelInformation": {
                     "parcelName": "Ellerbrock",
                     "parcelDimension": 75.6,
                     "startMonth": null,
                     "endMonth": null,
                     "productType": "Dairy cattle",
                     "numberOfEmployees": null,
                     "numberOfFulltimeEmployees": null,
                     "numberOfSeasonalEmployees": null,
                     "soilFractionSand": null,
                     "soilFractionClay": null,
                     "soilFractionSilt": null,
                     "bulkDensity": null,
                     "soilOrganicCarbon": null,
                     "numberOfAnimals": 247,
                     "numberOfPlants": null,
                     "livestockUnits": 3.27,
                     "numberOfBeehives": null,
                     "aquacultureArea": null
                  },
                  "datsUsed": [],
                  "waterUsageInformation": {
                     "totalWaterUsage": 4250,
                     "waterUsageForIrrigation": null,
                     "waterUsageForFertigation": null,
                     "waterUsageForPestDilution": null,
                     "waterUsageForCleaning": null,
                     "waterUsageForDrinking": null
                  },
                  "fuelUsageInformation": {
                     "totalFuelUsage": 17200,
                     "fuelUsageForFertilisation": null,
                     "fuelUsageForPesticides": null,
                     "fuelUsageForIrrigation": null,
                     "fuelUsageForSowing": null,
                     "fuelUsageForPruning": null,
                     "fuelUsageForTemperatureHumidityControl": null,
                     "fuelUsageForBeehivesVisits": null,
                     "fuelUsageForTransportingOysters": null,
                     "fuelUsageForMilking": null,
                     "fuelUsageForFeeding": null
                  },
                  "electricityUsageInformation": {
                     "totalElectricityUsage": 41000,
                     "electricityUsageForTemperatureHumidityControl": null,
                     "electricityUsageForIrrigation": null,
                     "electricityUsageForMilking": null,
                     "electricityUsageForHeatDetection": null,
                     "electricityUsageForCalvingDetection": null,
                     "electricityUsageForFeeding": null
                  },
                  "fuelForTemperatureControlInformation": [],
                  "pesticidesUsageInformation": [],
                  "fertilizersUsageInformation": [],
                  "feedUsageInformation": [
                     {
                        "productName": "Concentrate",
                        "quantity": 2000,
                        "productPrice": 21.2
                     }
                  ],
                  "drugsUsageInformation": [
                     {
                        "productName": "Tetracycline",
                        "quantity": 200,
                        "productPrice": 5.6
                     }
                  ],
                  "labourInformation": {
                     "labourForIrrigation": null,
                     "labourForPesticides": null,
                     "labourForFertilisation": null,
                     "labourForSowingOrPlanting": null,
                     "labourForPruning": null,
                     "labourForFieldVisits": null,
                     "labourForGreenhouseManagement": null,
                     "labourForQuantityTracking": null,
                     "labourForGrainQualityAssessment": null,
                     "labourForControllingPricesAndQuantities": null,
                     "labourForOrganisingLogistics": null,
                     "labourForCleaning": null,
                     "labourForStableVisits": null,
                     "labourForHeatDetection": null,
                     "labourForCalvingDetection": null,
                     "labourForPigstyManagement": null,
                     "labourForMilking": null,
                     "labourForMilkQualityAssessment": null,
                     "labourForFeeding": null,
                     "labourForBeehiveVisits": null,
                     "labourForOysterSampling": null,
                     "labourForOysterTransportation": null,
                     "labourForHarvesting": null,
                     "labourForStorage": null,
                     "labourForAdministration": null
                  },
                  "economicInformation": {
                     "numberOfFulfilledOrders": null,
                     "numberOfOrdersReceived": null,
                     "numberOfWrongOrders": null,
                     "additionalRevenues": null,
                     "percentageProteinInDryMatter": null,
                     "humidity": null,
                     "testWeight": null
                  },
                  "outputInformation": {
                     "cropProduction": null,
                     "milkProduction": 1192853,
                     "meatProduction": null,
                     "oysterProduction": null,
                     "honeyProduction": null,
                     "silosProduction": null,
                     "productMarketPrice": null,
                     "cropMarketPrice": null,
                     "meatMarketPrice": null,
                     "milkMarketPrice": 0.45,
                     "oysterMarketPrice": null,
                     "honeyMarketPrice": null
                  },
                  "additionalAnimalInformation": {
                     "numberOfDeathAnimals": 6,
                     "calvesDiedInFirst24Hours": 1,
                     "totalNumberOfCalvesBorn": 124,
                     "numberOfDaysWithPastureAccess": 0,
                     "outdoorLoafingArea": 0,
                     "herdSize": null,
                     "numberOfCowsWithHighSCCMilk": 0
                  },
                  "additionalLabourInformation": {
                     "numberOfNewInjuryCases": null,
                     "totalNumberOfLostWorkingHours": null,
                     "totalNumberOfWorkingHours": null,
                     "numberOfWorkingWeeks": null,
                     "numberOfNewLocalEmployeesHired": null,
                     "numberOfNewEmployeesHired": null
                  },
                  "additionalFieldsInformation": []
               },
               "parcelAssessmentWithoutDATS": {
                  "farmInformation": {
                     "farmNumber": 2,
                     "biogeographicalRegion": "Continental",
                     "totalFarmSize": 113
                  },
                  "parcelInformation": {
                     "parcelName": "Odenfelderhof",
                     "parcelDimension": 113,
                     "startMonth": null,
                     "endMonth": null,
                     "productType": "Dairy cattle",
                     "numberOfEmployees": 0,
                     "numberOfFulltimeEmployees": 0,
                     "numberOfSeasonalEmployees": 0,
                     "soilFractionSand": null,
                     "soilFractionClay": null,
                     "soilFractionSilt": null,
                     "bulkDensity": null,
                     "soilOrganicCarbon": null,
                     "numberOfAnimals": 234,
                     "numberOfPlants": null,
                     "livestockUnits": 2,
                     "numberOfBeehives": null,
                     "aquacultureArea": null
                  },
                  "datsUsed": [],
                  "waterUsageInformation": {
                     "totalWaterUsage": 5521,
                     "waterUsageForIrrigation": null,
                     "waterUsageForFertigation": null,
                     "waterUsageForPestDilution": null,
                     "waterUsageForCleaning": null,
                     "waterUsageForDrinking": null
                  },
                  "fuelUsageInformation": {
                     "totalFuelUsage": 14600,
                     "fuelUsageForFertilisation": null,
                     "fuelUsageForPesticides": null,
                     "fuelUsageForIrrigation": null,
                     "fuelUsageForSowing": null,
                     "fuelUsageForPruning": null,
                     "fuelUsageForTemperatureHumidityControl": null,
                     "fuelUsageForBeehivesVisits": null,
                     "fuelUsageForTransportingOysters": null,
                     "fuelUsageForMilking": null,
                     "fuelUsageForFeeding": null
                  },
                  "electricityUsageInformation": {
                     "totalElectricityUsage": 26079,
                     "electricityUsageForTemperatureHumidityControl": null,
                     "electricityUsageForIrrigation": null,
                     "electricityUsageForMilking": null,
                     "electricityUsageForHeatDetection": null,
                     "electricityUsageForCalvingDetection": null,
                     "electricityUsageForFeeding": null
